== Sending message to Servicebus and consume them

In this sample you'll use the Azure Servicebus source and sink Kamelet based on camel-azure-servicebus component.

=== Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

=== Setting up enviroment

Follow the instructions at https://github.com/oscerd/cloud-ready-kamelets[Alpine Linux (asciidoctor)] in iac/azure/servicebus

=== Setup credentials

In the `application.properties` add the correct accessKey, accountName and containerName for the Azure Storage Blob account.

=== How to run the producer

Then you can run this producer example using:

[source,sh]
----
$ jbang -Dcamel.jbang.version=4.5.0-SNAPSHOT camel run timer-to-azure-servicebus.yaml
----

=== How to run the consumer

Then you can run this consumer example using:

[source,sh]
----
$ jbang -Dcamel.jbang.version=4.5.0-SNAPSHOT camel run azure-servicebus-to-log.yaml
----

=== Verify the sink worked

After a while you should find different files with different name and date. Each of these file will contain two entries (one every 30 seconds).

